name: Build README

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "32 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node build_readme.mjs

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "readme-bot@users.noreply.github.com"
          git config --global user.name "README Bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated README content" && git push)
